apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hello-dotnet
  name: hello-dotnet
  namespace: default
spec:
  replicas: 1
  selector:
    app: hello-dotnet
  type: NodePort
  selector:
    matchLabels:
      run: hello-dotnet
  template:
    metadata:
      labels:
        run: hello-dotnet
    spec:
      containers:
      - name: HelloWorldAspNetCore
        image: helloworldaspnetcore:latest
        imagePullPolicy: Never
